/**
 * Mapping dictionaries for normalizing ExerciseDB API data
 * to the Pulse exercise catalog vocabulary.
 * All maps: ExerciseDB value (lowercase) → Pulse value.
 */

/** ExerciseDB bodyPart → Pulse body_part */
export const BODY_PART_MAP: Record<string, string> = {
  'back': 'back',
  'cardio': 'cardio',
  'chest': 'chest',
  'lower arms': 'lower arms',
  'lower legs': 'lower legs',
  'neck': 'neck',
  'shoulders': 'shoulders',
  'upper arms': 'upper arms',
  'upper legs': 'upper legs',
  'waist': 'core',
};

/** ExerciseDB target → Pulse target_muscle */
export const TARGET_MUSCLE_MAP: Record<string, string> = {
  'abductors': 'abductors',
  'abs': 'abdominals',
  'adductors': 'adductors',
  'biceps': 'biceps',
  'calves': 'calves',
  'cardiovascular system': 'cardiovascular',
  'delts': 'deltoids',
  'forearms': 'forearms',
  'glutes': 'glutes',
  'hamstrings': 'hamstrings',
  'lats': 'lats',
  'levator scapulae': 'levator scapulae',
  'pectorals': 'chest',
  'quads': 'quadriceps',
  'serratus anterior': 'serratus anterior',
  'spine': 'spinal erectors',
  'traps': 'trapezius',
  'triceps': 'triceps',
  'upper back': 'upper back',
};

/** ExerciseDB secondary muscle name → Pulse muscle name */
export const MUSCLE_NAME_MAP: Record<string, string> = {
  // Direct matches
  'abductors': 'abductors',
  'adductors': 'adductors',
  'biceps': 'biceps',
  'calves': 'calves',
  'forearms': 'forearms',
  'glutes': 'glutes',
  'hamstrings': 'hamstrings',
  'hip flexors': 'hip flexors',
  'lats': 'lats',
  'levator scapulae': 'levator scapulae',
  'obliques': 'obliques',
  'serratus anterior': 'serratus anterior',
  'triceps': 'triceps',
  'upper back': 'upper back',
  'infraspinatus': 'infraspinatus',
  'teres major': 'teres major',
  'teres minor': 'teres minor',
  'rhomboids': 'rhomboids',
  'brachialis': 'brachialis',
  'brachioradialis': 'brachioradialis',
  'tensor fasciae latae': 'tensor fasciae latae',
  'tibialis anterior': 'tibialis anterior',
  // Normalizations (multiple names → one canonical name)
  'abs': 'abdominals',
  'pectorals': 'chest',
  'quads': 'quadriceps',
  'delts': 'deltoids',
  'traps': 'trapezius',
  'spine': 'spinal erectors',
  'anterior deltoids': 'deltoids',
  'posterior deltoids': 'deltoids',
  'lateral deltoids': 'deltoids',
  'rear deltoids': 'deltoids',
  'wrist extensors': 'forearms',
  'wrist flexors': 'forearms',
  'soleus': 'calves',
  'gastrocnemius': 'calves',
  'rectus abdominis': 'abdominals',
  'transverse abdominis': 'abdominals',
  'lower back': 'spinal erectors',
  'erector spinae': 'spinal erectors',
  'gluteus medius': 'glutes',
  'gluteus maximus': 'glutes',
  'sartorius': 'quadriceps',
  'gracilis': 'adductors',
  'sternocleidomastoid': 'neck',
  'shoulders': 'deltoids',
  'chest': 'chest',
  'back': 'back',
  'core': 'abdominals',
  'lower abs': 'abdominals',
  'upper chest': 'chest',
  'latissimus dorsi': 'lats',
  'deltoids': 'deltoids',
  'quadriceps': 'quadriceps',
  'trapezius': 'trapezius',
  'abdominals': 'abdominals',
  'rotator cuff': 'infraspinatus',
  'grip muscles': 'forearms',
};

/** ExerciseDB equipment string → Pulse equipment name */
export const EQUIPMENT_MAP: Record<string, string> = {
  'barbell': 'Barbell',
  'olympic barbell': 'Barbell',
  'ez barbell': 'EZ Bar',
  'trap bar': 'Trap Bar',
  'dumbbell': 'Dumbbell',
  'cable': 'Cable Machine',
  'leverage machine': 'Machine (Plate-Loaded)',
  'sled machine': 'Machine (Plate-Loaded)',
  'hammer': 'Machine (Plate-Loaded)',
  'smith machine': 'Smith Machine',
  'assisted': 'Machine (Selectorized)',
  'skierg machine': 'Machine (Selectorized)',
  'upper body ergometer': 'Machine (Selectorized)',
  'elliptical machine': 'Machine (Selectorized)',
  'stationary bike': 'Machine (Selectorized)',
  'stepmill machine': 'Machine (Selectorized)',
  'body weight': 'Bodyweight',
  'weighted': 'Bodyweight',
  'band': 'Resistance Band',
  'resistance band': 'Resistance Band',
  'kettlebell': 'Kettlebell',
  'medicine ball': 'Medicine Ball',
  'stability ball': 'Stability Ball',
  'bosu ball': 'Bosu Ball',
  'rope': 'Cable Machine',
  'roller': 'Other',
  'wheel roller': 'Ab Wheel',
  'tire': 'Other',
};

/** Equipment name → category for creating new equipment rows */
export const EQUIPMENT_CATEGORY_MAP: Record<string, string> = {
  'Barbell': 'barbell',
  'EZ Bar': 'barbell',
  'Trap Bar': 'barbell',
  'Dumbbell': 'dumbbell',
  'Cable Machine': 'cable',
  'Machine (Plate-Loaded)': 'machine',
  'Machine (Selectorized)': 'machine',
  'Smith Machine': 'machine',
  'Bodyweight': 'bodyweight',
  'Resistance Band': 'band',
  'Kettlebell': 'kettlebell',
  'Medicine Ball': 'other',
  'Stability Ball': 'other',
  'Bosu Ball': 'other',
  'Ab Wheel': 'other',
  'Other': 'other',
};
